const tryAgain = ' Please check the logs for details and try again.';
export const DELETE_ABILITY_FAILED = `Error: the ability failed to delete.${tryAgain}`;
export const INVALID_STAT = 'Error: not a valid stat value. Please enter a numeric value.';
export const LOAD_ABILITIES_FAILED = `Error: abilities failed to load.${tryAgain}`;
export const LOAD_STATS_FAILED = `Error: stats failed to load.${tryAgain}`;
export const NO_ABILITIES_FOUND = 'You don\'t have any abilities yet - try adding some!';
export const NO_STATS_FOUND = 'Could not find any stats. Please check that the database and gateway are correctly configured.';
export const SAVE_ABILITY_FAILED = `Error: the ability failed to save.${tryAgain}`;
export const UPDATE_STAT_FAILED = ` failed to update.${tryAgain}`;
