export const CACHE_STAT = 'CACHE_STAT';
export const LOAD_STATS_SUCCESS = 'LOAD_STATS_SUCCESS';
export const POP_ERROR = 'POP_ERROR';
export const PUSH_ERROR = 'PUSH_ERROR';
export const REVERT_STAT = 'REVERT_STAT';
export const UPDATE_STAT_SUCCESS = 'UPDATE_STAT_SUCCESS';
